config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :buildings
  resources :landlords
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
end

app/models/landlord.rb
class Landlord < ApplicationRecord
end

app/models/tenant.rb
class Tenant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :set_landlord, only: %i[ show edit update destroy ]

  # GET /landlords or /landlords.json
  def index
    @landlords = Landlord.all
  end

  # GET /landlords/1 or /landlords/1.json
  def show
  end

  # GET /landlords/new
  def new
    @landlord = Landlord.new
  end

  # GET /landlords/1/edit
  def edit
  end

  # POST /landlords or /landlords.json
  def create
    @landlord = Landlord.new(landlord_params)

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: "Landlord was successfully created." }
        format.json { render :show, status: :created, location: @landlord }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landlords/1 or /landlords/1.json
  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to @landlord, notice: "Landlord was successfully updated." }
        format.json { render :show, status: :ok, location: @landlord }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1 or /landlords/1.json
  def destroy
    @landlord.destroy
    respond_to do |format|
      format.html { redirect_to landlords_url, notice: "Landlord was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def landlord_params
      params.require(:landlord).permit(:name, :cell, :email, :building_id)
    end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/landlords/_form.html.erb
<%= form_with(model: landlord) do |form| %>
  <% if landlord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(landlord.errors.count, "error") %> prohibited this landlord from being saved:</h2>

      <ul>
        <% landlord.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :cell %>
    <%= form.text_area :cell %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email %>
  </div>

  <div class="field">
    <%= form.label :building_id %>
    <%= form.number_field :building_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/landlords/edit.html.erb
<h1>Editing Landlord</h1>

<%= render 'form', landlord: @landlord %>

<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>

app/views/landlords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Landlords</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cell</th>
      <th>Email</th>
      <th>Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @landlords.each do |landlord| %>
      <tr>
        <td><%= landlord.name %></td>
        <td><%= landlord.cell %></td>
        <td><%= landlord.email %></td>
        <td><%= landlord.building_id %></td>
        <td><%= link_to 'Show', landlord %></td>
        <td><%= link_to 'Edit', edit_landlord_path(landlord) %></td>
        <td><%= link_to 'Destroy', landlord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Landlord', new_landlord_path %>

app/views/landlords/new.html.erb
<h1>New Landlord</h1>

<%= render 'form', landlord: @landlord %>

<%= link_to 'Back', landlords_path %>

app/views/landlords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @landlord.name %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @landlord.cell %>
</p>

<p>
  <strong>Email:</strong>
  <%= @landlord.email %>
</p>

<p>
  <strong>Building:</strong>
  <%= @landlord.building_id %>
</p>

<%= link_to 'Edit', edit_landlord_path(@landlord) %> |
<%= link_to 'Back', landlords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiLordofland</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>